/* Generated by Together */
package pentagoxl.spel;

public class Hok {

    private Veld[] velden;

    public Hok() {
        velden = new Veld[9];
        for (int i = 0; i < 9; i++)
            velden[i] = Veld.LEEG;
    }

    public Veld getVeld(int index) {
        return velden[index];
    }

    public Veld[] getVelden() {
        return velden;
    }

    public void draai(boolean klokMee) {
        Veld temp = velden[0];
        if (klokMee) {
            velden[0] = velden[3];
            velden[3] = velden[6];
            velden[6] = velden[7];
            velden[7] = velden[8];
            velden[8] = velden[5];
            velden[5] = velden[2];
            velden[2] = velden[1];
            velden[1] = temp;
        } else {
            velden[0] = velden[1];
            velden[1] = velden[2];
            velden[2] = velden[5];
            velden[5] = velden[8];
            velden[8] = velden[7];
            velden[7] = velden[6];
            velden[6] = velden[3];
            velden[3] = temp;
        }

    }

    @Override
    public String toString() {
        String toRet = "";
        for (Veld v : velden)
            toRet += ", " + v.toString();
        return toRet.substring(2);
    }
}
