/* Generated by Together */

package pentagoxl.spel;

public class Hok {
    public Veld getVeld(int index){ return velden[index]; }

    public Veld[] getVelden(){ return velden; }

    public void draai(boolean klokMee) {
    }

    /**
     * @supplierCardinality 0..9 
     */
    private Veld[] velden;
}
