/* Generated by Together */

package pentagoxl.spel;

public class Hok {
    public Veld getVelden(int index){ return velden[index]; }

    public Veld[] getVelden(){ return velden; }

    public void draai(boolean klokMee) {
    }

    private Veld[] velden;
}
