/* Generated by Together */
package pentagoxl.spel;

import pentagoxl.NetHandler;

public abstract class Speler {

    public abstract String getNaam();

    public Speler(NetHandler handler) {
        this.HANDLER = handler;
    }

    public int getAantalKnikkers() {
        return aantalKnikkers;
    }

    public Veld getVeld() {
        return veld;
    }

    public void setVeld(Veld veld) {
        this.veld = veld;
    }

    public abstract int[] doeZet(Bord bord);
    public Veld veld;
    public final NetHandler HANDLER;
    protected int aantalKnikkers;
}
