/* Generated by Together */

package pentagoxl.spel;
import java.util.List;
import java.util.Observable;

public class Spel extends Observable {
    public Bord getBord() { return bord; }

    public List getSpelers(){ return spelers; }

    public void setSpelers(List spelers){ this.spelers = spelers; }

    public boolean isOver() {
    }

    public void doeZet(int mark, int rotate) {
    }

    private Bord bord;
    private List spelers;
}
