/* Generated by Together */
package pentagoxl.spel;

import pentagoxl.NetHandler;

public abstract class Speler {

    public String getNaam() {
    	return name;
    }
    
    public void setNaam(String name) {
    	this.name = name;
    }

    public int getAantalKnikkers() {
        return aantalKnikkers;
    }

    public Veld getVeld() {
        return veld;
    }

    public void setVeld(Veld veld) {
        this.veld = veld;
    }

    public Veld veld;
    protected int aantalKnikkers;
    private String name;
}
