/* Generated by Together */

package pentagoxl.spel;
import pentagoxl.NetHandler;

public abstract class Speler {
    public abstract String getNaam();

    public int getAantalKnikkers() {
        return aantalKnikkers;
    }

    public abstract int[] doeZet(Bord bord);

    public final Veld VELD;
    public final NetHandler HANDLER;
    protected int aantalKnikkers;
}
