/* Generated by Together */

package pentagoxl.client;

import java.awt.GridLayout;

import javax.swing.*;
import pentagoxl.spel.Speler;
import pentagoxl.spel.Veld;

public class GUI extends JFrame implements ClientClient.Listener{
    
	public GUI() {
		super("PentagoXL");
		
		buildGUI();
		
		setVisible(true);
	}


    public static void main(String[] args) {
    	new GUI();
    }
	
	private void buildGUI(){
		setSize(600,420);		
		this.getContentPane().setLayout(new BoxLayout(this.getContentPane(), BoxLayout.Y_AXIS));
		
		//Panel which contains 9 other panels
		JPanel bordPanel = new JPanel(new GridLayout(3,3)); 
		this.getContentPane().add(bordPanel);
		
		//Array of panels which will contain the balls
		JPanel hokPanels[] = new JPanel[9];
		for (int i = 0; i < 9; i++) {
			hokPanels[i] = new JPanel(new GridLayout(3,3));
			bordPanel.add(hokPanels[i]);
		}
		
		//Array which contains every button
		JButton buttons[] = new JButton[81];
		for (int i = 0; i < 81; i++) {
			buttons[i] = new JButton(Veld.LEEG.toString());
			hokPanels[i/9].add(buttons[i]);
		}
	}

	@Override
	public void doTurn() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void gameStarting(Speler[] spelers) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void bordChanged() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void gameOver(Speler[] winnaars) {
		// TODO Auto-generated method stub
		
	}
	
	public void displayMessage(String msg) {
		
	}
}
