/* Generated by Together */
package pentagoxl;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.SocketException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.logging.Level;
import java.util.logging.Logger;
import pentagoxl.server.Server;

public class NetHandler {

    private Socket socket;
    private Sender mySender;
    private List<Listener> listeners;

    public NetHandler(Socket sock) throws IOException {
        this.socket = sock;
        mySender = new Sender();
        mySender.start();
        new Processor().start();
        listeners = new ArrayList<Listener>();
    }

    private class Sender extends Thread {

        private ConcurrentLinkedQueue<String> queue = new ConcurrentLinkedQueue<String>();
        private PrintWriter writer;

        private Sender() throws IOException {
            writer = new PrintWriter(socket.getOutputStream(), true);
        }

        @Override
        public synchronized void run() {
            while (!socket.isOutputShutdown()) {
                while (!queue.isEmpty() && !socket.isOutputShutdown()) {
                    String toSend = queue.poll();
                    logMessage(toSend, false); // DEBUG
                    writer.println(toSend);
                }
                try {
                    this.wait();
                } catch (InterruptedException e) {
                    // We don't care.
                }
            }
        }

        public void addMessageToQueue(String msg) {
            queue.add(msg);
            synchronized (this) {
                this.notifyAll();
            }
        }
    }

    private class Processor extends Thread {

        private BufferedReader reader;

        public Processor() throws IOException {
            this.reader = new BufferedReader(new InputStreamReader(socket.getInputStream()));
        }

        public void run() {
            while (!socket.isClosed() && !socket.isInputShutdown())
                try {
                    String in = reader.readLine();
                    logMessage(in, true); // DEBUG
                    if (in == null)
                        break; // LOLHAI
                    String[] cmdargs = ProtocolEndpoint.DELIMITER_PATTERN.split(in);
                    String cmd = cmdargs[0];
                    String[] args = null;
                    if (cmdargs.length > 1) {
                        args = new String[cmdargs.length - 1];
                        for (int i = 1; i < cmdargs.length; i++)
                            args[i - 1] = cmdargs[i];
                    }
                    for (Listener l : NetHandler.this.listeners)
                        l.onReceive(cmd, args);
                    
                } catch (SocketException e) {
                	break; //TODO fix, massive spam zonder deze catch als een client de verbinding verbreekt zonder quit
                } catch (IOException e) {
                    Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, e);
                } 
        }
    }

    public static interface Listener {

        public void onReceive(String cmd, String[] args);
    }

    public void addMessage(String cmd, String... args) {
        String message = cmd;
        for (String s : args) {
            message += pentagoxl.ProtocolEndpoint.DELIMITER;
            message += s;
        }

        mySender.addMessageToQueue(message);
    }

    /**
     * Builds a nack message. <br /> Will call
     * {@link #addMessage(java.lang.String, java.lang.String[]) }
     *
     * @param error <tt>Error to send</tt>
     */
    public void addNack(ProtocolError error) {
        addMessage(ProtocolEndpoint.SRV_NACK, error.getCode() + "");
    }

    public void addListener(Listener l) {
        listeners.add(l);
    }

    /**
     * Returns the socket this <tt>NetHander</tt> is using to communicate.
     *
     * @return A socket object
     */
    public Socket getSocket() {
        return socket;
    }

    private void logMessage(String msg, boolean incoming) {
        String naam = getSocket().getInetAddress().toString();
        String toPrint = naam + (incoming ? " > " : " < ") + msg;
        System.err.println(toPrint);
    }
}
