/* Generated by Together */
package pentagoxl.ai;

import pentagoxl.Client;
import pentagoxl.NetHandler;
import pentagoxl.spel.Bord;

public abstract class AI extends Client {

    public AI(NetHandler handler) {
        super(handler);
    }

    @Override
    public abstract int[] doeZet(Bord bord);
}
