/* Generated by Together */

package pentagoxl.ai;

import pentagoxl.NetHandler;
import pentagoxl.spel.Bord;

public class AIImplementation extends AI {

    public AIImplementation(NetHandler handler) {
        super(handler);
    }

    @Override
    public int[] doeZet(Bord bord) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void onReceive(String cmd, String[] args) {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
